var express = require('express')
var router = express.Router()
var token = require('../auth/VerifyTokens')
var customerCurd = require('../controllers/customers.controller')
router.get('/customers', token.checkAdminToken, customerCurd.home)
router.post('/customers/add', token.checkAdminToken, customerCurd.create)
router.get('/customers/add', token.checkAdminToken, customerCurd.showAddCustomerForm)
router.get('/customers/delete/(:employee_id)', token.checkAdminToken, customerCurd.deleteCustomer)
router.get('/customers/edit/(:employee_id)', token.checkAdminToken, customerCurd.showEditCustomerForm)
router.post('/customers/edit/(:employee_id)', token.checkAdminToken, customerCurd.updateCustomer)
module.exports = router